package utils

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClassifyReviewFile_LockFile(t *testing.T) {
	class := ClassifyReviewFile("package-lock.json")
	if !class.IsLockFile || !class.SkipForReview {
		t.Fatalf("expected lock file to be skipped for review: %+v", class)
	}
}

func TestClassifyReviewFile_GeneratedContent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "generated.go")
	content := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage test\n")
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}

	class := ClassifyReviewFile(path)
	if !class.IsGenerated || !class.SkipForReview {
		t.Fatalf("expected generated file to be skipped for review: %+v", class)
	}
}

func TestClassifyReviewFile_ExcessiveLineLength(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "minified.js")
	content := []byte("const x = \"" + strings.Repeat("a", generatedLineLengthThreshold+100) + "\";\n")
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}

	class := ClassifyReviewFile(path)
	if !class.IsGenerated || !class.SkipForReview {
		t.Fatalf("expected long-line file to be skipped for review: %+v", class)
	}
}
