package utils

import (
	"bufio"
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const generatedLineLengthThreshold = 2000

type ReviewFileClass struct {
	IsLockFile    bool
	IsGenerated   bool
	IsVendored    bool
	IsBinary      bool
	SkipForReview bool
}

var explicitLockFiles = map[string]struct{}{
	"package-lock.json": {},
	"yarn.lock":         {},
	"pnpm-lock.yaml":    {},
	"bun.lockb":         {},
	"Cargo.lock":        {},
	"Gemfile.lock":      {},
	"Pipfile.lock":      {},
	"poetry.lock":       {},
	"composer.lock":     {},
	"go.sum":            {},
	"Podfile.lock":      {},
}

var generatedMarkers = []string{
	"code generated by",
	"do not edit",
	"@generated",
	"automatically generated",
	"auto-generated",
}

func ClassifyReviewFile(path string) ReviewFileClass {
	class := ReviewFileClass{}
	base := filepath.Base(path)
	lowerBase := strings.ToLower(base)
	lowerPath := strings.ToLower(path)

	if _, ok := explicitLockFiles[base]; ok {
		class.IsLockFile = true
		class.SkipForReview = true
	} else if _, ok := explicitLockFiles[lowerBase]; ok {
		class.IsLockFile = true
		class.SkipForReview = true
	}

	if strings.Contains(lowerPath, "vendor/") || strings.Contains(lowerPath, "node_modules/") {
		class.IsVendored = true
		class.SkipForReview = true
	}

	attrs := getGitReviewAttributes(path)
	if attrs.generated {
		class.IsGenerated = true
	}
	if attrs.vendored {
		class.IsVendored = true
		class.SkipForReview = true
	}

	if looksLikeGeneratedPath(lowerPath) {
		class.IsGenerated = true
		class.SkipForReview = true
	}

	if content, err := os.ReadFile(path); err == nil {
		if isReviewBinaryContent(content) {
			class.IsBinary = true
			class.SkipForReview = true
		}
		if looksLikeGeneratedContent(content) {
			class.IsGenerated = true
			class.SkipForReview = true
		}
		if hasExcessiveLineLength(content, generatedLineLengthThreshold) {
			class.IsGenerated = true
			class.SkipForReview = true
		}
	}

	return class
}

func looksLikeGeneratedPath(lowerPath string) bool {
	patterns := []string{
		".min.", ".bundle.", ".dist.", ".generated.", ".pb.go", ".map",
		"bundle.js", "/dist/", "dist/", "/build/", "build/", "_generated.go", "_generated.",
	}
	for _, pattern := range patterns {
		if strings.Contains(lowerPath, pattern) {
			return true
		}
	}
	return false
}

func looksLikeGeneratedContent(content []byte) bool {
	sample := bytes.ToLower(content)
	if len(sample) > 4096 {
		sample = sample[:4096]
	}
	for _, marker := range generatedMarkers {
		if bytes.Contains(sample, []byte(marker)) {
			return true
		}
	}
	return false
}

func isReviewBinaryContent(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	sample := content
	if len(sample) > 1024 {
		sample = sample[:1024]
	}
	if bytes.IndexByte(sample, 0) >= 0 {
		return true
	}
	nonPrintable := 0
	for _, b := range sample {
		if (b < 32 || b > 126) && b != '\n' && b != '\r' && b != '\t' {
			nonPrintable++
		}
	}
	return float64(nonPrintable)/float64(len(sample)) > 0.3
}

func hasExcessiveLineLength(content []byte, threshold int) bool {
	if threshold <= 0 || len(content) == 0 {
		return false
	}

	scanner := bufio.NewScanner(bytes.NewReader(content))
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, max(threshold+1, 256*1024))
	for scanner.Scan() {
		if len(scanner.Bytes()) > threshold {
			return true
		}
	}
	return false
}

type gitReviewAttributes struct {
	generated bool
	vendored  bool
}

func getGitReviewAttributes(path string) gitReviewAttributes {
	cmd := exec.Command("git", "check-attr", "generated", "linguist-generated", "vendored", "linguist-vendored", "--", path)
	output, err := cmd.Output()
	if err != nil {
		return gitReviewAttributes{}
	}

	var attrs gitReviewAttributes
	for _, line := range strings.Split(string(output), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, ": ", 3)
		if len(parts) != 3 {
			continue
		}
		name := strings.TrimSpace(parts[1])
		value := strings.TrimSpace(parts[2])
		isTrue := value == "set" || value == "true"
		switch name {
		case "generated", "linguist-generated":
			attrs.generated = attrs.generated || isTrue
		case "vendored", "linguist-vendored":
			attrs.vendored = attrs.vendored || isTrue
		}
	}

	return attrs
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
