package configuration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sprout-foundry/sprout/pkg/envutil"
)

// CredentialsDirName is the subdirectory under the config dir that holds
// sensitive files (api_keys.json, key.age, mode files). Created 0700.
const CredentialsDirName = "credentials"

// GetConfigDir returns the configuration directory path
func GetConfigDir() (string, error) {
	return envutil.GetConfigDir()
}

// getDefaultConfigDir returns the config directory WITHOUT respecting
// SPROUT_CONFIG_DIR/SPROUT_CONFIG. Used internally during a layered
// load to resolve the "true global" providers dir — the scoped dir
// comes from the env var, and this must always return the home/XDG
// default so the two are distinguishable.
func getDefaultConfigDir() (string, error) {
	if xdg := strings.TrimSpace(os.Getenv("XDG_CONFIG_HOME")); xdg != "" {
		return filepath.Join(xdg, "sprout"), nil
	}
	if h := strings.TrimSpace(os.Getenv("HOME")); h != "" {
		return filepath.Join(h, ".config", "sprout"), nil
	}
	hd, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	return filepath.Join(hd, ".config", "sprout"), nil
}

// CredentialsDir returns the credentials subdirectory under the config
// root, creating it with mode 0700 if missing.
func CredentialsDir() (string, error) {
	configDir, err := GetConfigDir()
	if err != nil {
		return "", fmt.Errorf("get config dir for credentials: %w", err)
	}
	credDir := filepath.Join(configDir, CredentialsDirName)
	if err := os.MkdirAll(credDir, 0o700); err != nil {
		return "", fmt.Errorf("create credentials directory: %w", err)
	}
	return credDir, nil
}

// CredentialsDirFromDir returns the credentials subdirectory under an
// explicit base, creating it with mode 0700 if missing.
func CredentialsDirFromDir(base string) (string, error) {
	credDir := filepath.Join(base, CredentialsDirName)
	if err := os.MkdirAll(credDir, 0o700); err != nil {
		return "", fmt.Errorf("create credentials directory: %w", err)
	}
	return credDir, nil
}

// GetConfigPath returns the full path to the config file
func GetConfigPath() (string, error) {
	configDir, err := GetConfigDir()
	if err != nil {
		return "", fmt.Errorf("failed to get config directory: %w", err)
	}
	return filepath.Join(configDir, ConfigFileName), nil
}

// GetConfigLocalPath returns the path to the user-scope local override
// file (config.local.json). The file may not exist; callers should stat
// before reading.
func GetConfigLocalPath() (string, error) {
	configDir, err := GetConfigDir()
	if err != nil {
		return "", fmt.Errorf("failed to get config directory: %w", err)
	}
	return filepath.Join(configDir, ConfigLocalFileName), nil
}

// WorkspaceConfigDir returns the .sprout directory for a workspace root.
func WorkspaceConfigDir(workspaceRoot string) string {
	if workspaceRoot == "" {
		return ""
	}
	return filepath.Join(workspaceRoot, ConfigDirName)
}

// workspaceGitignoreContent is the .gitignore shipped into every
// workspace .sprout/ directory. It covers personal overrides and
// per-workspace state that should never be committed.
const workspaceGitignoreContent = `# Auto-generated by sprout — do not edit.
# Personal overrides (machine-specific settings)
*.local.json
# Per-workspace state directories
changes/
revisions/
runlogs/
bg-processes/
`

// EnsureWorkspaceConfigDir creates the workspace .sprout/ directory if
// missing and ships a .gitignore covering personal overrides and state
// directories. Idempotent — safe to call on every startup.
func EnsureWorkspaceConfigDir(workspaceRoot string) error {
	dir := WorkspaceConfigDir(workspaceRoot)
	if dir == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create workspace config directory: %w", err)
	}
	gitignorePath := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gitignorePath); err == nil {
		return nil
	}
	return os.WriteFile(gitignorePath, []byte(workspaceGitignoreContent), 0644)
}

// WorkspaceConfigWritePath returns where workspace-level config is written.
// Always the new filename — legacy files are read but never written back to.
func WorkspaceConfigWritePath(workspaceRoot string) string {
	if workspaceRoot == "" {
		return ""
	}
	return filepath.Join(workspaceRoot, ConfigDirName, WorkspaceConfigFileName)
}

// GetWorkspaceConfigPath returns the workspace-level config file to READ.
//
// Resolution: workspace.json if present, else the legacy config.json, else the
// workspace.json path (so callers can stat it and find nothing). Existing
// workspaces keep working untouched; nothing is moved or rewritten.
func GetWorkspaceConfigPath(workspaceRoot string) string {
	if workspaceRoot == "" {
		return ""
	}
	return ResolveWorkspaceConfigFile(WorkspaceConfigDir(workspaceRoot), isHomeDir(workspaceRoot))
}

// ResolveWorkspaceConfigFile picks the workspace config file inside dir.
//
// dirIsHome disables the legacy fallback. This is load-bearing: `.sprout` is
// the per-directory sprout folder AND ~/.sprout is the user-level state
// directory, so at $HOME the legacy config.json is the user's global config,
// not a workspace config. Falling back to it there is precisely the aliasing
// this split exists to remove — and every existing install has that file, so
// without this guard the split would fix nothing for current users.
//
// A user who deliberately runs with $HOME as the workspace still gets a real
// workspace layer; it just has to be an explicit ~/.sprout/workspace.json.
func ResolveWorkspaceConfigFile(dir string, dirIsHome bool) string {
	if dir == "" {
		return ""
	}
	current := filepath.Join(dir, WorkspaceConfigFileName)
	if _, err := os.Stat(current); err == nil {
		return current
	}
	if dirIsHome {
		return current
	}
	legacy := filepath.Join(dir, ConfigFileName)
	if _, err := os.Stat(legacy); err == nil {
		return legacy
	}
	return current
}

// isHomeDir reports whether dir resolves to the user's home directory.
// Symlinks are evaluated on both sides so macOS /Users → /private/Users (or a
// symlinked home) doesn't produce a false negative.
func isHomeDir(dir string) bool {
	if dir == "" {
		return false
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return false
	}
	resolvedDir, dirErr := filepath.EvalSymlinks(dir)
	resolvedHome, homeErr := filepath.EvalSymlinks(home)
	if dirErr != nil || homeErr != nil {
		return filepath.Clean(dir) == filepath.Clean(home)
	}
	return resolvedDir == resolvedHome
}

// IsWorkspaceConfigPresent checks if a workspace config file exists
func IsWorkspaceConfigPresent(workspaceRoot string) bool {
	path := GetWorkspaceConfigPath(workspaceRoot)
	if path == "" {
		return false
	}
	_, err := os.Stat(path)
	return err == nil
}
