package tools

// CommandCorpusEntry is a single labeled command in the embedding classifier's
// reference set. The embedding classifier (embedding_classifier.go) embeds each
// entry's Command and uses KNN to decide whether a heuristic CAUTION result
// should be downgraded to SAFE.
type CommandCorpusEntry struct {
	Command  string       // e.g. "npm test", "rm -rf node_modules", "git push --force"
	Label    SecurityRisk // SecuritySafe, SecurityCaution, SecurityDangerous
	Category string       // "test", "build", "cleanup", "network", "git", "dangerous"
}

// DefaultCommandCorpus returns the labeled reference commands used to seed the
// embedding classifier's vector store. These cover common development workflows.
//
// The corpus is deliberately weighted toward SAFE commands (~85%) because the
// classifier's purpose is to rescue safe commands that the heuristic over-flags
// (e.g. "npm test" caught by the catch-all CAUTION default). The DANGEROUS
// counterexamples anchor the KNN so that destructive commands are never rescued.
func DefaultCommandCorpus() []CommandCorpusEntry {
	return []CommandCorpusEntry{
		// --- Test runners (SAFE) ---
		{"npm test", SecuritySafe, "test"},
		{"npm run test", SecuritySafe, "test"},
		{"yarn test", SecuritySafe, "test"},
		{"pnpm test", SecuritySafe, "test"},
		{"go test ./...", SecuritySafe, "test"},
		{"go test -v ./...", SecuritySafe, "test"},
		{"go test -race ./...", SecuritySafe, "test"},
		{"go test -run TestFoo ./...", SecuritySafe, "test"},
		{"go test -count=1 ./...", SecuritySafe, "test"},
		{"go test -timeout 120s ./...", SecuritySafe, "test"},
		{"pytest", SecuritySafe, "test"},
		{"pytest -v", SecuritySafe, "test"},
		{"pytest -x", SecuritySafe, "test"},
		{"python -m pytest", SecuritySafe, "test"},
		{"python -m pytest -v", SecuritySafe, "test"},
		{"cargo test", SecuritySafe, "test"},
		{"cargo test --release", SecuritySafe, "test"},
		{"cargo test -- --nocapture", SecuritySafe, "test"},
		{"make test", SecuritySafe, "test"},
		{"make test-unit", SecuritySafe, "test"},
		{"jest", SecuritySafe, "test"},
		{"jest --coverage", SecuritySafe, "test"},
		{"vitest", SecuritySafe, "test"},
		{"vitest run", SecuritySafe, "test"},
		{"vitest --coverage", SecuritySafe, "test"},
		{"mocha", SecuritySafe, "test"},
		{"deno test", SecuritySafe, "test"},
		{"dotnet test", SecuritySafe, "test"},
		{"gradle test", SecuritySafe, "test"},
		{"mvn test", SecuritySafe, "test"},

		// --- Build / compile (SAFE) ---
		{"go build ./...", SecuritySafe, "build"},
		{"go build -o bin/app", SecuritySafe, "build"},
		{"go build -o sprout .", SecuritySafe, "build"},
		{"npm run build", SecuritySafe, "build"},
		{"yarn build", SecuritySafe, "build"},
		{"pnpm build", SecuritySafe, "build"},
		{"npm run dev", SecuritySafe, "build"},
		{"cargo build", SecuritySafe, "build"},
		{"cargo build --release", SecuritySafe, "build"},
		{"make", SecuritySafe, "build"},
		{"make build", SecuritySafe, "build"},
		{"make build-all", SecuritySafe, "build"},
		{"make all", SecuritySafe, "build"},
		{"tsc", SecuritySafe, "build"},
		{"tsc --noEmit", SecuritySafe, "build"},
		{"webpack", SecuritySafe, "build"},
		{"vite build", SecuritySafe, "build"},
		{"rollup -c", SecuritySafe, "build"},
		{"esbuild bundle.js", SecuritySafe, "build"},
		{"cmake --build .", SecuritySafe, "build"},
		{"cmake ..", SecuritySafe, "build"},
		{"dotnet build", SecuritySafe, "build"},
		{"gradle build", SecuritySafe, "build"},
		{"swift build", SecuritySafe, "build"},
		{"zig build", SecuritySafe, "build"},

		// --- Lint / format (SAFE) ---
		{"gofmt -w .", SecuritySafe, "lint"},
		{"goimports -w .", SecuritySafe, "lint"},
		{"golangci-lint run", SecuritySafe, "lint"},
		{"staticcheck ./...", SecuritySafe, "lint"},
		{"eslint .", SecuritySafe, "lint"},
		{"eslint --fix .", SecuritySafe, "lint"},
		{"prettier --write .", SecuritySafe, "lint"},
		{"prettier --check .", SecuritySafe, "lint"},
		{"black .", SecuritySafe, "lint"},
		{"black --check .", SecuritySafe, "lint"},
		{"isort .", SecuritySafe, "lint"},
		{"ruff check .", SecuritySafe, "lint"},
		{"ruff format .", SecuritySafe, "lint"},
		{"mypy .", SecuritySafe, "lint"},
		{"pylint *.py", SecuritySafe, "lint"},
		{"flake8 .", SecuritySafe, "lint"},
		{"cargo fmt", SecuritySafe, "lint"},
		{"cargo clippy", SecuritySafe, "lint"},
		{"rustfmt", SecuritySafe, "lint"},
		{"shfmt -w .", SecuritySafe, "lint"},
		{"npx prettier --write .", SecuritySafe, "lint"},
		{"stylua .", SecuritySafe, "lint"},
		{"rubocop", SecuritySafe, "lint"},

		// --- Package managers — install to local project (SAFE) ---
		{"npm install", SecuritySafe, "package"},
		{"npm install pkg", SecuritySafe, "package"},
		{"npm ci", SecuritySafe, "package"},
		{"npm i", SecuritySafe, "package"},
		{"npm i pkg", SecuritySafe, "package"},
		{"yarn install", SecuritySafe, "package"},
		{"yarn add pkg", SecuritySafe, "package"},
		{"pnpm install", SecuritySafe, "package"},
		{"pnpm add pkg", SecuritySafe, "package"},
		{"go get pkg", SecuritySafe, "package"},
		{"go get -u pkg", SecuritySafe, "package"},
		{"go mod tidy", SecuritySafe, "package"},
		{"go mod download", SecuritySafe, "package"},
		{"go mod vendor", SecuritySafe, "package"},
		{"cargo add pkg", SecuritySafe, "package"},
		{"pip install -r requirements.txt", SecuritySafe, "package"},
		{"pip install pkg", SecuritySafe, "package"},
		{"pip install --upgrade pkg", SecuritySafe, "package"},
		{"poetry install", SecuritySafe, "package"},
		{"poetry add pkg", SecuritySafe, "package"},
		{"bundle install", SecuritySafe, "package"},
		{"bundle add pkg", SecuritySafe, "package"},
		{"composer install", SecuritySafe, "package"},
		{"deno install", SecuritySafe, "package"},

		// --- Common read-only dev commands (SAFE) ---
		{"ls -la", SecuritySafe, "read"},
		{"ls -lh", SecuritySafe, "read"},
		{"cat file.txt", SecuritySafe, "read"},
		{"head -n 20 file", SecuritySafe, "read"},
		{"tail -n 20 file", SecuritySafe, "read"},
		{"wc -l file", SecuritySafe, "read"},
		{"grep pattern file", SecuritySafe, "read"},
		{"grep -r pattern .", SecuritySafe, "read"},
		{"find . -name '*.go'", SecuritySafe, "read"},
		{"find . -type f -name '*.py'", SecuritySafe, "read"},
		{"fd pattern", SecuritySafe, "read"},
		{"rg pattern", SecuritySafe, "read"},
		{"rg -i pattern src/", SecuritySafe, "read"},
		{"du -sh .", SecuritySafe, "read"},
		{"du -sh *", SecuritySafe, "read"},
		{"df -h", SecuritySafe, "read"},
		{"free -h", SecuritySafe, "read"},
		{"ps aux", SecuritySafe, "read"},
		{"top -bn1", SecuritySafe, "read"},
		{"echo hello", SecuritySafe, "read"},
		{"printf 'hello'", SecuritySafe, "read"},
		{"pwd", SecuritySafe, "read"},
		{"which go", SecuritySafe, "read"},
		{"which node", SecuritySafe, "read"},
		{"env", SecuritySafe, "read"},
		{"printenv", SecuritySafe, "read"},
		{"date", SecuritySafe, "read"},
		{"uname -a", SecuritySafe, "read"},
		{"whoami", SecuritySafe, "read"},
		{"hostname", SecuritySafe, "read"},

		// --- Safe cleanup (main false-positive rescue targets) ---
		{"rm -rf node_modules", SecuritySafe, "cleanup"},
		{"rm -rf dist", SecuritySafe, "cleanup"},
		{"rm -rf build", SecuritySafe, "cleanup"},
		{"rm -rf target", SecuritySafe, "cleanup"},
		{"rm -rf .next", SecuritySafe, "cleanup"},
		{"rm -rf .nuxt", SecuritySafe, "cleanup"},
		{"rm -rf out", SecuritySafe, "cleanup"},
		{"rm -rf bin", SecuritySafe, "cleanup"},
		{"rm -rf obj", SecuritySafe, "cleanup"},
		{"rm -rf coverage", SecuritySafe, "cleanup"},
		{"rm -rf .cache", SecuritySafe, "cleanup"},
		{"rm -rf .turbo", SecuritySafe, "cleanup"},
		{"rm -rf tmp", SecuritySafe, "cleanup"},
		{"rm -rf temp", SecuritySafe, "cleanup"},
		{"rm -rf __pycache__", SecuritySafe, "cleanup"},
		{"rm -rf .pytest_cache", SecuritySafe, "cleanup"},
		{"rm -rf .mypy_cache", SecuritySafe, "cleanup"},
		{"rm -rf .ruff_cache", SecuritySafe, "cleanup"},
		{"rm -rf .gradle", SecuritySafe, "cleanup"},
		{"rm -rf .svelte-kit", SecuritySafe, "cleanup"},
		{"rm foo.txt", SecuritySafe, "cleanup"},
		{"rm temp.log", SecuritySafe, "cleanup"},
		{"rm *.tmp", SecuritySafe, "cleanup"},
		{"rm -r old-dir", SecuritySafe, "cleanup"},
		{"make clean", SecuritySafe, "cleanup"},
		{"make distclean", SecuritySafe, "cleanup"},
		{"go clean -cache", SecuritySafe, "cleanup"},
		{"go clean -testcache", SecuritySafe, "cleanup"},
		{"cargo clean", SecuritySafe, "cleanup"},

		// --- Network — safe fetches (SAFE) ---
		{"curl -s https://example.com/api", SecuritySafe, "network"},
		{"curl -o file.tar.gz https://example.com/file.tar.gz", SecuritySafe, "network"},
		{"curl -fsSL https://example.com/install.sh", SecuritySafe, "network"},
		{"wget https://example.com/file.tar.gz", SecuritySafe, "network"},
		{"wget -q https://example.com/file", SecuritySafe, "network"},
		{"git clone https://github.com/user/repo.git", SecuritySafe, "network"},
		{"git clone --depth 1 https://github.com/user/repo.git", SecuritySafe, "network"},
		{"gh repo clone user/repo", SecuritySafe, "network"},
		{"ssh-keygen -t ed25519", SecuritySafe, "network"},
		{"ping -c 3 example.com", SecuritySafe, "network"},
		{"dig example.com", SecuritySafe, "network"},
		{"nslookup example.com", SecuritySafe, "network"},

		// --- Safe git operations (SAFE) ---
		{"git status", SecuritySafe, "git"},
		{"git log --oneline -10", SecuritySafe, "git"},
		{"git diff", SecuritySafe, "git"},
		{"git diff --stat", SecuritySafe, "git"},
		{"git show HEAD", SecuritySafe, "git"},
		{"git branch", SecuritySafe, "git"},
		{"git branch -a", SecuritySafe, "git"},
		{"git fetch origin", SecuritySafe, "git"},
		{"git pull", SecuritySafe, "git"},
		{"git add file.go", SecuritySafe, "git"},
		{"git stash", SecuritySafe, "git"},
		{"git stash list", SecuritySafe, "git"},
		{"git tag", SecuritySafe, "git"},
		{"git remote -v", SecuritySafe, "git"},

		// --- DANGEROUS counterexamples (anchor KNN — never rescue these) ---
		{"rm -rf /", SecurityDangerous, "dangerous"},
		{"rm -rf ~", SecurityDangerous, "dangerous"},
		{"rm -rf /*", SecurityDangerous, "dangerous"},
		{"rm -rf $HOME", SecurityDangerous, "dangerous"},
		{"rm -rf ../", SecurityDangerous, "dangerous"},
		{"rm -rf ../../", SecurityDangerous, "dangerous"},
		{"sudo rm -rf /", SecurityDangerous, "dangerous"},
		{"sudo rm -rf /etc", SecurityDangerous, "dangerous"},
		{"mkfs.ext4 /dev/sda", SecurityDangerous, "dangerous"},
		{"dd if=/dev/zero of=/dev/sda", SecurityDangerous, "dangerous"},
		{"dd if=/dev/urandom of=/dev/sda", SecurityDangerous, "dangerous"},
		{"chmod -R 777 /", SecurityDangerous, "dangerous"},
		{"chmod -R 777 ~", SecurityDangerous, "dangerous"},
		{"chmod -R 777 /etc", SecurityDangerous, "dangerous"},
		{":(){ :|:& };:", SecurityDangerous, "dangerous"},
		{"fork bomb", SecurityDangerous, "dangerous"},
		{"shutdown -h now", SecurityDangerous, "dangerous"},
		{"reboot", SecurityDangerous, "dangerous"},
		{"init 0", SecurityDangerous, "dangerous"},
		{"shutdown -r now", SecurityDangerous, "dangerous"},
		{"fdisk /dev/sda", SecurityDangerous, "dangerous"},
		{"parted /dev/sda", SecurityDangerous, "dangerous"},
		{"gparted", SecurityDangerous, "dangerous"},

		// --- CAUTION tier (genuinely need user attention — do not rescue) ---
		{"git push --force", SecurityCaution, "git"},
		{"git push --force-with-lease", SecurityCaution, "git"},
		{"git push -f origin main", SecurityCaution, "git"},
		{"git branch -D main", SecurityCaution, "git"},
		{"git reset --hard origin/main", SecurityCaution, "git"},
		{"git clean -fdx", SecurityCaution, "git"},
		{"git filter-branch -- HEAD", SecurityCaution, "git"},
		{"docker rm -f $(docker ps -aq)", SecurityCaution, "docker"},
		{"docker system prune -af", SecurityCaution, "docker"},
		{"docker volume rm $(docker volume ls -q)", SecurityCaution, "docker"},
		{"docker rmi $(docker images -q)", SecurityCaution, "docker"},
		{"sudo apt install pkg", SecurityCaution, "install"},
		{"sudo apt-get install pkg", SecurityCaution, "install"},
		{"sudo yum install pkg", SecurityCaution, "install"},
		{"sudo dnf install pkg", SecurityCaution, "install"},
		{"eval $(cat env.sh)", SecurityCaution, "eval"},
	}
}
