package api

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/sprout-foundry/sprout/pkg/credentials"
	"github.com/sprout-foundry/sprout/pkg/envutil"

	agenterrors "github.com/sprout-foundry/sprout/pkg/errors"
)

// ClientInterface defines the common interface for all API clients.
//
// The ctx on Send* methods is forwarded to the underlying HTTP request
// (via http.NewRequestWithContext) so callers can abort in-flight LLM
// calls when the user clicks Stop. See SP-034 for the design.
type ClientInterface interface {
	SendChatRequest(ctx context.Context, messages []Message, tools []Tool, reasoning string, disableThinking bool) (*ChatResponse, error)
	SendChatRequestStream(ctx context.Context, messages []Message, tools []Tool, reasoning string, disableThinking bool, callback StreamCallback) (*ChatResponse, error)
	CheckConnection() error
	SetDebug(debug bool)
	SetModel(model string) error
	GetModel() string
	GetProvider() string
	GetModelContextLimit() (int, error)
	ListModels(ctx context.Context) ([]ModelInfo, error)
	SupportsVision() bool
	// SupportsConversationalVision reports whether the model is suitable as
	// the inline multimodal target for chat-format vision messages. Some
	// models (OCR-only, e.g. glm-ocr) accept image input but produce
	// extraction outputs unsuitable for free-form multimodal conversation.
	// Defaults to true when SupportsVision() is true.
	SupportsConversationalVision() bool
	// VisionCapabilities returns the per-provider vision limits (max bytes
	// per image, max images per request, max dimension, supported detail
	// tiers). Zero-valued fields mean "unknown — use default". Concrete
	// implementations populate this with provider-specific data; callers
	// should pass the result through VisionCapabilitiesOrDefault() before
	// reading individual fields. SP-103-D3 / AUDIT-GAP-2.
	VisionCapabilities() VisionCapabilities
	GetVisionModel() string
	SendVisionRequest(ctx context.Context, messages []Message, tools []Tool, reasoning string, disableThinking bool) (*ChatResponse, error)
	// TPS (Tokens Per Second) tracking methods
	GetLastTPS() float64
	GetAverageTPS() float64
	GetTPSStats() map[string]float64
	ResetTPSStats()
}

// ClientType represents the type of client to use
type ClientType string

// Special providers that don't have configs (or have special behavior)
const (
	OllamaClientType      ClientType = "ollama" // Alias for ollama-local
	OllamaLocalClientType ClientType = "ollama-local"
	OllamaCloudClientType ClientType = "ollama-cloud"
	TestClientType        ClientType = "test"   // Mock provider for CI/testing
	EditorClientType      ClientType = "editor" // Editor-only mode, no AI provider
)

// Built-in provider names (ClientType constants) are maintained here to provide type-safe constants.
// These are kept in sync with provider_gen.go (generated by go generate from provider configs).
// When adding a new provider, update both the provider config and add a ClientType constant here.
//
// Use providers.AllProviderNames(), providers.KnownProviders(), or providers.ProviderDisplayNames()
// to get the list of providers without hardcoding them in this package.
const (
	OpenAIClientType     ClientType = "openai"
	OpenRouterClientType ClientType = "openrouter"
	ZAIClientType        ClientType = "zai"
	DeepInfraClientType  ClientType = "deepinfra"
	DeepSeekClientType   ClientType = "deepseek"
	LMStudioClientType   ClientType = "lmstudio"
	MistralClientType    ClientType = "mistral"
	MinimaxClientType    ClientType = "minimax"
	ChutesClientType     ClientType = "chutes"
	CerebrasClientType   ClientType = "cerebras"
	ZAICodingClientType  ClientType = "zai-coding"
)

// NewUnifiedClient creates a client with default model for the provider
func NewUnifiedClient(clientType ClientType) (ClientInterface, error) {
	return NewUnifiedClientWithModel(clientType, "")
}

// NewUnifiedClientWithModel creates a client with a specific model
func NewUnifiedClientWithModel(clientType ClientType, model string) (ClientInterface, error) {
	// Use external factory to avoid import cycles
	return nil, errors.New("use factory.CreateProviderClient instead to avoid import cycles")
}

// NewDeepInfraClientWrapper creates a DeepInfra client wrapper
func NewDeepInfraClientWrapper(model string) (ClientInterface, error) {
	return nil, errors.New("DeepInfra client wrapper removed - use providers.NewDeepInfraProviderWithModel instead")
}

// NewOpenRouterClientWrapper is deprecated - use factory.CreateProviderClient instead
func NewOpenRouterClientWrapper(model string) (ClientInterface, error) {
	return nil, errors.New("OpenRouter client wrapper deprecated - use factory.CreateProviderClient instead")
}

// NewDeepSeekClientWrapper creates a DeepSeek client wrapper
// DeepSeek provider removed (unimplemented)

// DetermineProvider provides unified provider detection with clear precedence:
// 1. Command-line flag (if provided)
// 2. Environment variable (SPROUT_PROVIDER, with LEDIT_PROVIDER backward-compat)
// 3. Config file (last_used_provider)
//
// Returns an error if no available provider is found; callers should surface
// this to the user and offer interactive provider selection.
func DetermineProvider(explicitProvider string, lastUsedProvider ClientType) (ClientType, error) {
	// 1. Command-line flag has highest priority
	if explicitProvider != "" {
		provider, err := ParseProviderName(explicitProvider)
		if err != nil {
			return "", agenterrors.NewValidation(fmt.Sprintf("invalid provider '%s': %v", explicitProvider, err), nil)
		}
		if !IsProviderAvailable(provider) {
			return "", agenterrors.NewConfig(fmt.Sprintf("provider '%s' is not available (check API key)", explicitProvider), nil)
		}
		return provider, nil
	}

	// 2. Environment variable
	if providerEnv := envutil.GetEnvSimple("PROVIDER"); providerEnv != "" {
		provider, err := ParseProviderName(providerEnv)
		if err == nil && IsProviderAvailable(provider) {
			return provider, nil
		}
	}

	// 3. Last used provider from config
	if lastUsedProvider != "" && IsProviderAvailable(lastUsedProvider) {
		return lastUsedProvider, nil
	}

	return "", fmt.Errorf("no provider available: no explicit provider, SPROUT_PROVIDER env var, or configured provider with valid credentials found")
}

// ParseProviderName converts a string provider name to ClientType
// Handles special aliases and validates provider names.
func ParseProviderName(name string) (ClientType, error) {
	normalized := strings.ToLower(strings.TrimSpace(name))

	// Handle special aliases first (these are not in provider configs)
	switch normalized {
	case "ollama":
		// "ollama" maps to ollama-local
		return OllamaLocalClientType, nil
	case "test":
		return TestClientType, nil
	case "editor":
		return EditorClientType, nil
	case "":
		return "", agenterrors.NewValidation("provider name cannot be empty", nil)
	}

	// For other providers, return as ClientType - validation happens later
	// This allows for custom providers and new providers to be discovered
	return ClientType(normalized), nil
}

// IsProviderAvailable checks if a provider can be used.
// Uses credentials.HasProviderCredential to avoid hardcoding env var strings.
func IsProviderAvailable(provider ClientType) bool {
	return credentials.HasProviderCredential(string(provider))
}

// GetProviderName returns the human-readable name for a provider
func GetProviderName(clientType ClientType) string {
	// Mapping of provider client types to display names
	// This is kept in sync with providers.ProviderDisplayNames() to avoid circular dependencies
	providerDisplayNames := map[ClientType]string{
		OpenAIClientType:      "OpenAI",
		OpenRouterClientType:  "OpenRouter (Recommended)",
		ZAIClientType:         "Z.AI",
		ZAICodingClientType:   "GLM Coding Plan",
		DeepInfraClientType:   "DeepInfra",
		DeepSeekClientType:    "DeepSeek",
		LMStudioClientType:    "LM Studio",
		MistralClientType:     "Mistral",
		MinimaxClientType:     "MiniMax",
		ChutesClientType:      "Chutes",
		CerebrasClientType:    "Cerebras",
		OllamaCloudClientType: "Ollama (Cloud)",
		OllamaLocalClientType: "Ollama (Local)",
		TestClientType:        "Test Provider",
		EditorClientType:      "Editor Mode",
	}

	// Check if we have a display name for this provider
	if displayName, ok := providerDisplayNames[clientType]; ok {
		return displayName
	}

	// Handle the "ollama" alias that maps to ollama-local
	if string(clientType) == "ollama" {
		return "Ollama (Local)"
	}

	// Fallback to string representation for unknown/custom providers
	return string(clientType)
}

// DeepInfraClientWrapper is deprecated - use providers.NewDeepInfraProviderWithModel directly
