package embedding

import (
	"os"
	"path/filepath"
	"testing"
)

// TestByteLevelTokenizerMatchesHF verifies that the Go ByteLevelTokenizer
// produces identical token IDs to HuggingFace's tokenizers library for a set
// of code and natural-language inputs. This is the correctness gate for the
// tokenizer — if the IDs match, the ONNX embeddings will be correct.
//
// Opt-in: SPROUT_TOKENIZER_TEST=1 (requires the Jina tokenizer.json staged).
func TestByteLevelTokenizerMatchesHF(t *testing.T) {
	if os.Getenv("SPROUT_TOKENIZER_TEST") != "1" {
		t.Skip("SPROUT_TOKENIZER_TEST unset")
	}

	tokenizerPath := filepath.Join(DefaultModelDir(), "jina-code-v2", "tokenizer.json")
	if _, err := os.Stat(tokenizerPath); err != nil {
		t.Skipf("jina-code-v2 tokenizer not staged at %s", tokenizerPath)
	}

	tok, err := NewByteLevelTokenizer(tokenizerPath)
	if err != nil {
		t.Fatalf("tokenizer: %v", err)
	}

	// Reference token IDs from HF tokenizers (jinaai/jina-embeddings-v2-base-code).
	// Generated by: tokenizer(text, add_special_tokens=False)['input_ids']
	cases := []struct {
		name  string
		text  string
		hfIDs []int32
	}{
		{
			"simple Go function",
			"func SumInts(values []int) int {\n\ttotal := 0\n\tfor _, v := range values {\n\t\ttotal += v\n\t}\n\treturn total\n}",
			[]int32{1474, 21102, 35267, 12, 3001, 2516, 384, 13, 577, 297, 203, 202, 3637, 1594, 325, 203, 202, 1013, 6446, 358, 1594, 2685, 2012, 297, 316, 202, 3637, 1314, 358, 203, 202, 97, 203, 202, 525, 4126, 203, 97},
		},
		{
			"near-duplicate function",
			"func AddNumbers(nums []int) int {\n\tsum := 0\n\tfor _, n := range nums {\n\t\tsum += n\n\t}\n\treturn sum\n}",
			[]int32{1474, 2382, 16495, 12, 26478, 2516, 384, 13, 577, 297, 203, 202, 1155, 1594, 325, 203, 202, 1013, 6446, 321, 1594, 2685, 32033, 297, 316, 202, 1155, 1314, 321, 203, 202, 97, 203, 202, 525, 5949, 203, 97},
		},
		{
			"unrelated handler",
			"func Handler(name string, count int) string {\n\tif count <= 0 {\n\t\treturn \"none\"\n\t}\n\treturn name\n}",
			[]int32{1474, 16509, 12, 507, 964, 16, 2235, 577, 13, 964, 297, 203, 202, 311, 2235, 2483, 325, 297, 316, 202, 525, 331, 3561, 6, 203, 202, 97, 203, 202, 525, 667, 203, 97},
		},
		{
			"NL query",
			"sort an array of integers in place",
			[]int32{3203, 692, 1061, 438, 17991, 338, 4177},
		},
		{
			"NL query 2",
			"compute the sha256 hash of a string",
			[]int32{7101, 329, 11655, 3702, 3257, 438, 323, 964},
		},
		{
			"short text",
			"hello world",
			[]int32{9522, 7550},
		},
		{
			"empty-ish",
			"  ",
			[]int32{261},
		},
		{
			"special chars",
			"a <= b && c != d",
			[]int32{69, 2483, 328, 742, 283, 786, 364},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			goIDs := tok.Encode(tc.text)
			if len(goIDs) != len(tc.hfIDs) {
				t.Errorf("token count mismatch: Go=%d HF=%d\n  Go: %v\n  HF: %v",
					len(goIDs), len(tc.hfIDs), goIDs, tc.hfIDs)
				return
			}
			for i, want := range tc.hfIDs {
				if goIDs[i] != want {
					t.Errorf("token[%d]: Go=%d HF=%d (Go: %v, HF: %v)",
						i, goIDs[i], want, goIDs, tc.hfIDs)
					return
				}
			}
			t.Logf("✓ %d tokens match HF exactly", len(goIDs))
		})
	}
}
