// genapi writes the versioned OpenAPI contract (docs/api/openapi.yaml) from
// the Huma operations registered in pkg/webui. The document is generated, not
// hand-edited, so it cannot drift from the handlers: the hand-written seed
// (docs/api/openapi.base.yaml, the reference families not yet migrated to
// Huma) is merged with the fresh Huma operations, and the result is written to
// docs/api/openapi.yaml. A test in this package fails when the committed file
// is stale.
//
// Regenerate after changing the seed or registering a Huma operation:
//
//	go run ./cmd/genapi
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/sprout-foundry/sprout/pkg/webui"
)

// Contract-relative paths the generator reads and writes. The generator walks
// up to the repo root (the directory holding go.mod) and joins these onto it.
const (
	// baseRel is the hand-written seed: the reference families not yet
	// migrated to Huma. It is the stable source of the non-generated content.
	baseRel = "docs/api/openapi.base.yaml"
	// outRel is the generated contract. It is regenerated on every run, so it
	// is a pure function of (seed + registered Huma operations) and can be
	// byte-compared for staleness.
	outRel = "docs/api/openapi.yaml"
)

// generatedHeader is the preamble written above the YAML body. It marks the
// file as generated and points at the two sources and the staleness gate.
const generatedHeader = `# Generated file — do not edit by hand.
#
# This OpenAPI contract is generated by cmd/genapi from two sources:
#
#   - docs/api/openapi.base.yaml — the hand-written seed (the reference
#     families not yet migrated to Huma);
#   - the Huma operations registered in pkg/webui/routes.go (via
#     webui.HumaOpenAPIDoc).
#
# Regenerate after changing either source with:
#
#     go run ./cmd/genapi
#
# A Go test in cmd/genapi fails when this file is stale.
`

// main is the CLI entry point: it resolves the repo root, generates the
// document in memory, and writes it to docs/api/openapi.yaml.
func main() {
	root, err := findRepoRoot(".")
	if err != nil {
		fmt.Fprintf(os.Stderr, "genapi: %v\n", err)
		os.Exit(1)
	}
	doc, err := Generate(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genapi: %v\n", err)
		os.Exit(1)
	}
	outPath := filepath.Join(root, outRel)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil { // #nosec G301 -- outPath resolves within the repo root
		fmt.Fprintf(os.Stderr, "genapi: create doc dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, doc, 0o644); err != nil { // #nosec G306 -- outPath resolves within the repo root
		fmt.Fprintf(os.Stderr, "genapi: write doc: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", outPath)
}

// Generate builds the merged OpenAPI document (header + YAML) in memory from
// the repo root. It is deterministic (sorted keys, canonical number
// rendering) so a staleness test can byte-compare it against the committed
// file. It never writes.
func Generate(root string) ([]byte, error) {
	baseBytes, err := os.ReadFile(filepath.Join(root, baseRel)) // #nosec G304 -- baseRel is a fixed repo-relative path
	if err != nil {
		return nil, fmt.Errorf("read seed %s: %w", baseRel, err)
	}
	base, err := unmarshalDoc(baseBytes)
	if err != nil {
		return nil, fmt.Errorf("parse seed %s: %w", baseRel, err)
	}
	humaDoc, err := webui.HumaOpenAPIDoc()
	if err != nil {
		return nil, fmt.Errorf("generate Huma operations: %w", err)
	}
	merged := mergeDocs(base, humaDoc)
	normalizeNumbers(merged)

	body, err := marshalDoc(merged)
	if err != nil {
		return nil, fmt.Errorf("render document: %w", err)
	}
	return []byte(generatedHeader + string(body)), nil
}

// findRepoRoot walks up from start until it finds a directory containing a
// go.mod (the repo root), returning an error if none is found.
func findRepoRoot(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", fmt.Errorf("resolve working directory: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil { // #nosec G304 -- dir is a walked-up path
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found walking up from %s", start)
		}
		dir = parent
	}
}
