import type { CloudEndpoint } from '../types';

/**
 * Category (b) — foundry-backend: Must be proxied to the Foundry backend.
 */
export const foundryBackendEndpoints: CloudEndpoint[] = [
  {
    path: '/api/query',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Main chat/query endpoint (needs Foundry proxy)',
  },
  {
    path: '/api/query/steer',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Steer agent mid-conversation',
  },
  {
    path: '/api/query/stop',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Stop agent execution',
  },
  {
    path: '/api/query/status',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Query execution status',
  },
  {
    path: '/api/upload/image',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Image upload for vision',
  },
  {
    path: '/api/embedding-index',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Embedding index status (needs backend vector DB)',
  },
  {
    path: '/api/providers/models',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List available models for providers',
  },
  {
    path: '/api/search/semantic/status',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Semantic search index status (needs backend)',
  },
  {
    path: '/api/search/semantic/build',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Build semantic search index (needs backend)',
  },
  {
    path: '/api/search/semantic/preview',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Preview semantic search index (needs backend)',
  },
  {
    path: '/api/search/semantic',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Semantic/vector search (needs backend AI infrastructure)',
  },
  {
    path: '/api/terminal/agent-sessions',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List background agent terminal sessions (needs backend)',
  },
  {
    path: '/api/terminal/agent-sessions/',
    methods: ['GET', 'POST'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'Agent session actions (output, attach, kill) — needs backend',
  },
  {
    path: '/api/git/status',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Git status',
  },
  {
    path: '/api/git/branches',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List git branches',
  },
  {
    path: '/api/git/checkout',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Checkout branch/commit',
  },
  {
    path: '/api/git/branch/create',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Create branch',
  },
  {
    path: '/api/git/pull',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Git pull',
  },
  {
    path: '/api/git/push',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Git push',
  },
  {
    path: '/api/git/stage',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Stage files',
  },
  {
    path: '/api/git/unstage',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Unstage files',
  },
  {
    path: '/api/git/discard',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Discard changes',
  },
  {
    path: '/api/git/stage-all',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Stage all files',
  },
  {
    path: '/api/git/unstage-all',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Unstage all files',
  },
  {
    path: '/api/git/commit',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Git commit',
  },
  {
    path: '/api/git/commit-message',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Generate commit message',
  },
  {
    path: '/api/git/revert',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Revert commit',
  },
  {
    path: '/api/git/deep-review',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Deep review',
  },
  {
    path: '/api/git/deep-review/fix',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Fix review items',
  },
  {
    path: '/api/git/deep-review/fix/start',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Start fix process',
  },
  {
    path: '/api/git/deep-review/fix/status',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Fix process status',
  },
  {
    path: '/api/git/diff',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Git diff',
  },
  {
    path: '/api/git/log',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Git log',
  },
  {
    path: '/api/git/confirm',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Confirm git commit',
  },
  {
    path: '/api/git/commit/show',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Show commit details',
  },
  {
    path: '/api/git/commit/show/file',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Show file diff in commit',
  },
  {
    path: '/api/git/worktrees',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List worktrees',
  },
  {
    path: '/api/git/worktree/create',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Create worktree',
  },
  {
    path: '/api/git/worktree/remove',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Remove worktree',
  },
  {
    path: '/api/git/worktree/checkout',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Checkout worktree',
  },
  {
    path: '/api/diagnostics',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Language diagnostics',
  },
  {
    path: '/api/semantic',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Semantic operations (go-to-def, hover, references, rename, completion)',
  },
  {
    path: '/api/lsp/status',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'LSP server status',
  },
  {
    path: '/api/lsp/ws',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'LSP WebSocket bridge',
  },
  {
    path: '/api/chat-sessions',
    methods: ['GET', 'POST'],
    category: 'foundry-backend',
    description: 'Chat session management',
  },
  {
    path: '/api/chat-sessions/create',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Create chat session',
  },
  {
    path: '/api/chat-sessions/delete',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Delete chat session',
  },
  {
    path: '/api/chat-sessions/delete-all',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Delete all chat sessions',
  },
  {
    path: '/api/chat-sessions/rename',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Rename chat session',
  },
  {
    path: '/api/chat-sessions/switch',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Switch chat session',
  },
  {
    path: '/api/chat-sessions/create-in-worktree',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Create session in worktree',
  },
  {
    path: '/api/chat-sessions/compact',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Compact chat session',
  },
  {
    path: '/api/chat-sessions/pin',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Pin chat session',
  },
  {
    path: '/api/chat-sessions/unpin',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Unpin chat session',
  },
  {
    path: '/api/chat-sessions/worktree-mappings',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List worktree mappings',
  },
  {
    path: '/api/chat-session/',
    methods: ['GET', 'POST'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'Worktree sub-endpoints',
  },
  {
    path: '/api/history/changelog',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'History changelog',
  },
  {
    path: '/api/history/revision',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'History revision',
  },
  {
    path: '/api/history/changes',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'History changes',
  },
  {
    path: '/api/history/rollback',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Rollback conversation history',
  },
  {
    path: '/api/sessions/restore',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Restore session state',
  },
  {
    path: '/api/sessions',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List sessions',
  },
  {
    path: '/api/settings',
    methods: ['GET', 'PUT'],
    category: 'foundry-backend',
    description: 'User settings (Foundry manages)',
  },
  {
    path: '/api/settings/mcp',
    methods: ['GET', 'PUT'],
    category: 'foundry-backend',
    description: 'MCP settings',
  },
  {
    path: '/api/settings/mcp/servers/',
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'MCP server CRUD',
  },
  {
    path: '/api/settings/credentials',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Get credentials (Foundry manages)',
  },
  {
    path: '/api/settings/credentials/',
    methods: ['GET', 'PUT', 'DELETE', 'POST'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'Credential CRUD (includes pool and test sub-paths)',
  },
  {
    path: '/api/settings/providers',
    methods: ['GET', 'PUT'],
    category: 'foundry-backend',
    description: 'Provider settings',
  },
  {
    path: '/api/settings/providers/',
    methods: ['GET', 'PUT', 'DELETE'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'Provider CRUD',
  },
  {
    path: '/api/settings/skills',
    methods: ['GET', 'PUT'],
    category: 'foundry-backend',
    description: 'Skill settings',
  },
  {
    path: '/api/settings/subagent-types',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Subagent type configs',
  },
  {
    path: '/api/settings/subagent-types/',
    methods: ['GET', 'PUT', 'DELETE'],
    category: 'foundry-backend',
    isPrefix: true,
    description: 'Subagent type CRUD',
  },
  {
    path: '/api/hotkeys',
    methods: ['GET', 'PUT'],
    category: 'foundry-backend',
    description: 'Hotkey configuration',
  },
  {
    path: '/api/hotkeys/validate',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Validate hotkey binding',
  },
  {
    path: '/api/hotkeys/preset',
    methods: ['POST'],
    category: 'foundry-backend',
    description: 'Apply hotkey preset',
  },
  {
    path: '/api/costs/summary',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Cost summary',
  },
  {
    path: '/api/costs/history',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Cost history',
  },
  {
    path: '/api/costs/detail',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Cost detail',
  },
  {
    path: '/api/providers',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'List available providers',
  },
  {
    path: '/api/stats',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Execution stats',
  },
  {
    path: '/api/workspace/symbols',
    methods: ['GET'],
    category: 'foundry-backend',
    description: 'Workspace symbols (LSP)',
  },
];
