import type { CloudEndpoint } from '../types';

/**
 * Category (c) — synthetic: Should return pre-defined synthetic responses.
 *
 * These responses MUST match the Go server stub responses in
 * platform/internal/api/webui_compat.go so that both the client-side
 * CloudAdapter interception and the server-side handlers return identical data.
 */
export const syntheticEndpoints: CloudEndpoint[] = [
  {
    path: '/api/onboarding/status',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { setup_required: false, onboarding_complete: true, providers: [] },
    description: 'Onboarding status (cloud is pre-configured)',
  },
  {
    path: '/api/onboarding/complete',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { message: 'ok' },
    description: 'Complete onboarding',
  },
  {
    path: '/api/onboarding/skip',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { message: 'ok' },
    description: 'Skip onboarding',
  },
  {
    path: '/api/instances',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { instances: [] },
    description: 'List instances (no local instances in cloud mode)',
  },
  {
    path: '/api/instances/ssh-hosts',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { hosts: [] },
    description: 'List SSH hosts (not available in cloud mode)',
  },
  {
    path: '/api/instances/ssh-open',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'SSH not available in cloud mode' },
    description: 'Open SSH workspace (not available in cloud mode)',
  },
  {
    path: '/api/instances/ssh-sessions',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { sessions: [] },
    description: 'List SSH sessions (not available in cloud mode)',
  },
  {
    path: '/api/instances/ssh-browse',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'SSH not available in cloud mode' },
    description: 'Browse SSH directory (not available in cloud mode)',
  },
  {
    path: '/api/instances/ssh-close',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { message: 'ok' },
    description: 'Close SSH session',
  },
  {
    path: '/api/instances/select',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Instance management not available in cloud mode' },
    description: 'Select instance (not available in cloud mode)',
  },
  {
    path: '/api/instances/ssh-launch-status',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { in_progress: false },
    description: 'SSH launch status',
  },
  {
    path: '/api/support-bundle',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { error: 'Support bundles not available in cloud mode' },
    description: 'Support bundle (not available in cloud mode)',
  },
  {
    path: '/api/config',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: {},
    description: 'App config (empty in cloud mode)',
  },
  {
    path: '/api/workspace',
    methods: ['GET', 'POST'],
    category: 'synthetic',
    // NOTE: This response intentionally omits is_project, needs_workspace_selection,
    // suggested_projects, and recent_workspaces. The consuming code (workspaceApi.ts
    // toWorkspaceResponse) defaults these to false/[] via nullish coalescing.
    // In cloud mode, workspace selection is not needed — the WASM shell owns the
    // virtual filesystem root, so needs_workspace_selection is effectively false.
    syntheticResponse: { message: 'ok', workspace_root: '/home/user', daemon_root: '/home/user' },
    description: 'Workspace info (cloud mode: WASM shell owns workspace, virtual FS root)',
  },

  // ── Endpoints not available in browser mode ─────────────────────
  // These return a consistent "not available" response instead of hitting
  // the platform backend which would return 401/404 and trigger error toasts.
  {
    path: '/api/providers/models',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { models: [] },
    description: 'Provider model listing (not available in browser mode)',
  },
  {
    path: '/api/upload/image',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Image upload not available in browser mode' },
    description: 'Image upload for vision (not available in browser mode)',
  },
  {
    path: '/api/search/semantic',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { results: [] },
    description: 'Semantic search (not available in browser mode)',
  },
  {
    path: '/api/search/semantic/status',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { indexed: false, error: 'Semantic search not available in browser mode' },
    description: 'Semantic search index status (not available in browser mode)',
  },
  {
    path: '/api/search/semantic/build',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Semantic search not available in browser mode' },
    description: 'Build semantic index (not available in browser mode)',
  },
  {
    path: '/api/search/semantic/preview',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Semantic search not available in browser mode' },
    description: 'Preview semantic index (not available in browser mode)',
  },
  {
    path: '/api/embedding-index',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { indexed: false, error: 'Embedding index not available in browser mode' },
    description: 'Embedding index status (not available in browser mode)',
  },
  {
    path: '/api/diagnostics',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { diagnostics: [], error: 'LSP diagnostics not available in browser mode' },
    description: 'Language diagnostics (not available in browser mode)',
  },
  {
    path: '/api/semantic',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'LSP semantic operations not available in browser mode' },
    description: 'Semantic operations — go-to-def, hover etc (not available in browser mode)',
  },
  {
    path: '/api/lsp/status',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { running: false, error: 'LSP not available in browser mode' },
    description: 'LSP server status (not available in browser mode)',
  },
  {
    path: '/api/lsp/ws',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { error: 'LSP WebSocket not available in browser mode' },
    description: 'LSP WebSocket bridge (not available in browser mode)',
  },
  {
    path: '/api/workspace/symbols',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { symbols: [], error: 'Workspace symbols not available in browser mode' },
    description: 'Workspace symbols via LSP (not available in browser mode)',
  },
  {
    path: '/api/costs/summary',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { total_cost: 0, query_count: 0, token_in: 0, token_out: 0 },
    description: 'Cost summary (not available in browser mode)',
  },
  {
    path: '/api/costs/history',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { entries: [] },
    description: 'Cost history (not available in browser mode)',
  },
  {
    path: '/api/costs/detail',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { details: [] },
    description: 'Cost detail (not available in browser mode)',
  },
  {
    path: '/api/sessions/restore',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Session restore not available in browser mode' },
    description: 'Restore session (not available in browser mode)',
  },
  {
    path: '/api/sessions',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { sessions: [] },
    description: 'Session list (not available in browser mode)',
  },
  {
    path: '/api/history/changelog',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { entries: [] },
    description: 'Changelog history (not available in browser mode)',
  },
  {
    path: '/api/history/revision',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'History revision not available in browser mode' },
    description: 'History revision (not available in browser mode)',
  },
  {
    path: '/api/history/changes',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { changes: [] },
    description: 'History changes (not available in browser mode)',
  },
  {
    path: '/api/history/rollback',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'History rollback not available in browser mode' },
    description: 'Rollback history (not available in browser mode)',
  },
  {
    path: '/api/settings/subagent-types',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { subagent_types: {} },
    description: 'Subagent type configs (not available in browser mode)',
  },
  {
    path: '/api/settings/subagent-types/',
    methods: ['GET'],
    category: 'synthetic',
    isPrefix: true,
    syntheticResponse: { subagent_types: {} },
    description: 'Subagent type read-only (not available in browser mode)',
  },
  {
    path: '/api/settings/mcp',
    methods: ['GET', 'PUT'],
    category: 'synthetic',
    syntheticResponse: { enabled: false, config: {} },
    description: 'MCP settings (not available in browser mode)',
  },
  {
    path: '/api/settings/mcp/servers/',
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
    category: 'synthetic',
    isPrefix: true,
    syntheticResponse: { servers: [], error: 'MCP servers not available in browser mode' },
    description: 'MCP server CRUD (not available in browser mode)',
  },
  {
    path: '/api/settings/skills',
    methods: ['GET', 'PUT'],
    category: 'synthetic',
    syntheticResponse: { skills: {} },
    description: 'Skill settings (not available in browser mode)',
  },
  {
    path: '/api/hotkeys',
    methods: ['GET', 'PUT'],
    category: 'synthetic',
    syntheticResponse: { hotkeys: {} },
    description: 'Hotkey configuration (not available in browser mode)',
  },
  {
    path: '/api/hotkeys/validate',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { valid: true },
    description: 'Hotkey validation (not available in browser mode)',
  },
  {
    path: '/api/hotkeys/preset',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { hotkeys: {} },
    description: 'Hotkey preset (not available in browser mode)',
  },

  // ── Chat session endpoints handled by WASM shell, not platform ──
  {
    path: '/api/chat-sessions/create-in-worktree',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Worktree sessions not available in browser mode' },
    description: 'Create session in worktree (not available in browser mode)',
  },
  {
    path: '/api/chat-sessions/compact',
    methods: ['POST'],
    category: 'synthetic',
    syntheticResponse: { error: 'Session compaction not available in browser mode' },
    description: 'Compact chat session (not available in browser mode)',
  },
  {
    path: '/api/chat-sessions/worktree-mappings',
    methods: ['GET'],
    category: 'synthetic',
    syntheticResponse: { mappings: [] },
    description: 'Worktree mappings (not available in browser mode)',
  },
  {
    path: '/api/chat-session/',
    methods: ['GET', 'POST'],
    category: 'synthetic',
    isPrefix: true,
    syntheticResponse: { error: 'Sub-session endpoints not available in browser mode' },
    description: 'Chat session worktree sub-endpoints (not available in browser mode)',
  },
];
