#!/bin/bash
set -e

echo "Creating commit..."

# Stage all changes
git add -A

# Create commit message
COMMIT_MESSAGE="fix: Implement solution for issue #$ISSUE_NUMBER

This commit addresses the requirements outlined in issue #$ISSUE_NUMBER.
Changes were generated by the ledit AI agent based on the issue description,
comments, and any attached images or mockups.

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

# Commit changes
git commit -m "$COMMIT_MESSAGE"

# Get commit SHA
COMMIT_SHA=$(git rev-parse HEAD)
echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

echo "Commit created: $COMMIT_SHA"