#!/bin/bash
set -e

echo "Managing pull request..."

# Push changes to remote
echo "Pushing changes to remote..."
git push -u origin "$BRANCH_NAME"

# Check if PR already exists
EXISTING_PR=$(gh pr list --base main --head "$BRANCH_NAME" --json number --jq '.[0].number' || echo "")

if [ -n "$EXISTING_PR" ]; then
    echo "Pull request #$EXISTING_PR already exists, updating..."
    
    # Add a comment about the update
    gh pr comment "$EXISTING_PR" --body "🔄 **Updated with new changes**

The ledit agent has made additional changes based on the latest requirements.

Commit: $(git rev-parse --short HEAD)"
    
    PR_NUMBER="$EXISTING_PR"
    PR_URL=$(gh pr view "$EXISTING_PR" --json url -q '.url')
else
    echo "Creating new pull request..."
    
    # Create PR body
    PR_BODY="## 🤖 Automated Solution for Issue #$ISSUE_NUMBER

This pull request was automatically generated by the [ledit AI issue solver](https://github.com/alantheprice/ledit) to resolve issue #$ISSUE_NUMBER.

### 📋 Issue Summary
Please see issue #$ISSUE_NUMBER for full context.

### 🔧 Changes Made
The AI agent analyzed the issue description, comments, and any attached images to implement this solution.

$(git log --oneline origin/main.."$BRANCH_NAME" | sed 's/^/- /')

### 📁 Files Changed
\`\`\`
$(git diff --name-status origin/main..."$BRANCH_NAME")
\`\`\`

### ✅ Review Checklist
- [ ] Code follows repository conventions and style
- [ ] Tests have been added/updated as needed
- [ ] Documentation has been updated if required
- [ ] No sensitive information or credentials exposed

### 🤝 Next Steps
1. Review the changes carefully
2. Run tests to ensure everything works
3. Request changes if needed via PR comments
4. Approve and merge when satisfied

---
**Automated by**: ledit v$(ledit --version 2>/dev/null || echo "latest")
**Model**: $AI_MODEL via $AI_PROVIDER
**Issue**: Closes #$ISSUE_NUMBER"

    # Create the PR
    PR_OUTPUT=$(gh pr create \
        --title "fix: Resolve issue #$ISSUE_NUMBER" \
        --body "$PR_BODY" \
        --base main \
        --head "$BRANCH_NAME" \
        --assignee "@me")
    
    # Extract PR number and URL
    PR_URL="$PR_OUTPUT"
    PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
fi

# Output results
echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
echo "pr-url=$PR_URL" >> $GITHUB_OUTPUT

# Add comment to issue
gh issue comment "$ISSUE_NUMBER" --body "🎉 I've created pull request #$PR_NUMBER to address this issue.

🔗 **Pull Request**: $PR_URL

Please review the proposed changes and let me know if any adjustments are needed."

echo "Pull request ready: $PR_URL"