package design

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Token export (SP-140-5 §5a): turn the design/tokens/*.tokens.json DTCG
// tiers into code-side artifacts under design/generated/. This file is the
// pure DTCG -> text half — no filesystem reads, no ToolEnv, no I/O beyond the
// directory-tree helpers at the bottom — so every target's output is unit
// testable without a workspace. The design_export_tokens ToolHandler is a thin
// wrapper around it (pkg/agent_tools/design_export_handler.go).
//
// The hard requirement is deterministic, byte-identical output: the same token
// inputs must produce identical bytes on every run and every platform,
// regardless of map iteration order or file read order. Everything below sorts
// by name before it emits, so the only things that can vary the bytes are the
// token values themselves. Note that filepath.Glob's lexical ordering is a
// POSIX convenience, not a cross-platform guarantee; platform-independent
// determinism comes from the post-hoc sort in ResolveExportTokens, not from the
// read order.
//
// Scope note: this file covers items 5.1 and 5.2. Item 5.2 adds two things:
// (1) every generated artifact opens with a provenance header carrying the
// content hash of the token inputs (TokenExportInputHash) so a consumer can
// verify design/code consistency offline at any checkout (SP-140 invariant 2,
// SP-140-5 §5f); and (2) ResolveExportTokens refuses a dirty alias graph
// (dangling/cyclic aliases) with a structured DirtyAliasError naming the
// offending token, rather than emitting broken var()/*token* references
// (SP-140-5 §5a). Both are deterministic — no timestamps — so the 5.1
// byte-identical guarantee still holds.

// export_artifacts.go — the artifact/provenance/hashing/writing half of
// token export: ExportedArtifact, provenance headers, content hashes, and
// WriteExportedArtifacts, split out of export.go.

// provenanceHeader renders the SP-140 invariant 2 provenance banner for one
// generated artifact, in the target's comment syntax. It is a fixed,
// newline-terminated block: an opening line naming the tool and target, the
// source-hash line carrying the token-input content hash (§5f: recomputable
// offline at any checkout), and a fixed terminator so a reader can extract it
// without parsing the language.
//
// Determinism is absolute: every line is either a constant or the input hash.
// There is deliberately no timestamp, host, or version — the same token inputs
// must produce byte-identical files on every run and every machine, and a
// timestamp would break both the byte-identity guarantee and the offline
// recomputation the header exists to enable.
//
// Style per target: /* ... */ block comments for the CSS targets (which open
// with "/*" and close on the terminator line), "//" line comments for TS,
// Swift, and Kotlin. Both are valid in the artifact's own language, so the
// generated file still compiles/parses with the banner in place.
func provenanceHeader(target, inputHash string) string {
	if inputHash == "" {
		inputHash = "unhashed"
	}
	prefix := headerCommentPrefix(target)
	open, close := "//", ""
	if prefix == "/*" {
		open, close = "/*", " */"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%s Generated by design_export_tokens (target=%s). Do not edit by hand.%s\n",
		open, target, close)
	fmt.Fprintf(&b, "%s source-hash: %s%s\n", prefix, inputHash, close)
	fmt.Fprintf(&b, "%s Source: design/tokens/*.tokens.json (W3C DTCG). Recompute the hash from those bytes to verify.%s\n",
		prefix, close)
	if close != "" {
		// The block comment already closed on the last content line; nothing
		// more to emit.
		return b.String()
	}
	fmt.Fprintf(&b, "%s sprout:end-provenance\n", prefix)
	return b.String()
}

// headerCommentPrefix returns the comment opener for a target's comment style.
func headerCommentPrefix(target string) string {
	switch target {
	case ExportTargetCSS, ExportTargetTailwind:
		return "/*"
	default:
		return "//"
	}
}

// ExportedArtifact is one written (or to-be-written) generated file.
type ExportedArtifact struct {
	// Target is the exporter that produced it (css, ts, ...).
	Target string
	// RelPath is the workspace-relative slash path (design/generated/<file>).
	RelPath string
	// Content is the exact byte content written.
	Content []byte
	// Hash is the deterministic content hash (see tokenExportArtifactHash).
	Hash string
}

// RenderArtifacts renders every target into memory without touching the
// filesystem, in canonical target order. The handler uses this to precheck and
// write each file; tests use it to assert byte-identical output.
func RenderArtifacts(tokens *TokenExport, targets []ExportTarget) ([]ExportedArtifact, error) {
	artifacts := make([]ExportedArtifact, 0, len(targets))
	for _, target := range targets {
		content, err := RenderExport(target.Name, tokens)
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, ExportedArtifact{
			Target:  target.Name,
			RelPath: filepath.ToSlash(filepath.Join(DirName, GeneratedSubdir, target.File)),
			Content: content,
			Hash:    tokenExportArtifactHash(content),
		})
	}
	return artifacts, nil
}

// TokenExportSourceHash is the label prefix on every content hash this package
// emits. It names the algorithm in-band so a consumer reading a header knows
// how to recompute the digest without reading the implementation.
const TokenExportSourceHashLabel = "fnv1a64"

// tokenExportHash computes the FNV-1a 64-bit digest of data and renders it as
// "fnv1a64:<16 hex digits>". FNV-1a is deliberate (SP-140-5 §5f): it is
// dependency-free, stable across runs, platforms, and Go versions — a consumer
// at an arbitrary checkout can recompute the same digest offline from the
// tree alone — and this is a staleness/consistency check, not a security
// boundary, so a cryptographic digest buys nothing.
func tokenExportHash(data []byte) string {
	const (
		offset64 = 14695981039346656037
		prime64  = 1099511628211
	)
	var h uint64 = offset64
	for _, c := range data {
		h ^= uint64(c)
		h *= prime64
	}
	return fmt.Sprintf("%s:%016x", TokenExportSourceHashLabel, h)
}

// TokenExportInputHash hashes the *token inputs* — the DTCG source documents
// the export read, not the rendered artifact. It is the authoritative
// provenance hash recorded in every generated artifact's header
// (SP-140 invariant 2, SP-140-5 §5f "provenance at any ref").
//
// Why inputs and not artifact bytes: the header must be identical across the
// five targets (only the rendering differs, the semantic content does not), and
// it has to be recomputable without re-running the export. A consumer at an
// arbitrary checkout recomputes it with:
//
//	exportTokenSourceHash(dir(os.ReadFile(design/tokens/*.tokens.json)))
//
// — i.e. concat the raw bytes of design/tokens/*.tokens.json sorted by
// basename, hash that. Nothing else (no timestamps, no paths, no env) feeds
// the digest, so it is deterministic across machines and checkouts.
//
// Each document is folded in as "len(bytes)\n bytes" so two different file
// partitions cannot concatenate to the same byte stream and collide.
func TokenExportInputHash(docs []TokenExportSource) string {
	var b bytes.Buffer
	for _, doc := range docs {
		fmt.Fprintf(&b, "%d\n", len(doc.Content))
		b.Write(doc.Content)
	}
	return tokenExportHash(b.Bytes())
}

// TokenExportSource is one DTCG token source document as read from disk: its
// workspace-relative slash path (design/tokens/<name>.tokens.json) and its
// exact bytes. Collected by ResolveExportTokens and retained on the
// TokenExport so the provenance header can be built from the same read that
// produced the leaves (no second filesystem pass, no chance of drift).
type TokenExportSource struct {
	// Path is the workspace-relative slash path of the source document.
	Path string
	// Name is the source document's base name (color.tokens.json); it is the
	// stable sort key, so the hash does not depend on the workspace root.
	Name string
	// Content is the document's exact bytes.
	Content []byte
}

// exportTokenInputHash computes the provenance hash over a set of source
// documents in name order, so two read orders cannot produce two hashes. It is
// the single place the canonical ordering lives.
func exportTokenInputHash(sources []TokenExportSource) string {
	ordered := append([]TokenExportSource(nil), sources...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })
	return TokenExportInputHash(ordered)
}

// tokenExportArtifactHash is the content hash of a *rendered artifact's* bytes
// (including its provenance header). It is the deterministic identity of the
// emitted file — two runs over the same tokens hash equal, and any single-byte
// change to the output moves it — which is what the handler reports per file
// (designExportFile.ContentHash) so a caller can tell whether a write actually
// changed anything.
func tokenExportArtifactHash(content []byte) string {
	return tokenExportHash(content)
}

// WriteExportedArtifacts writes each artifact (already rendered and carrying
// its final design-relative slash path in RelPath) under root, creating parent
// directories as needed. It returns an error on the first failure.
//
// Every RelPath must be confined to design/ — the handler asserts this before
// calling (relocateArtifacts + resolveExportOutDir), and this function
// re-checks it so a future caller cannot use it to escape the tree. Writes are
// plain file writes; the handler has prechecked every target path already.
func WriteExportedArtifacts(root string, artifacts []ExportedArtifact) error {
	return WriteExportedArtifactsAt(root, artifacts)
}

// WriteExportedArtifactsAt is WriteExportedArtifacts under its explicit name:
// it writes artifacts at their own RelPath, which the handler has already
// relocated to the requested output directory. Keeping both names lets the
// handler read naturally while the default-path helper stays for tests.
func WriteExportedArtifactsAt(root string, artifacts []ExportedArtifact) error {
	for _, a := range artifacts {
		clean := strings.TrimSuffix(filepath.ToSlash(filepath.Clean(a.RelPath)), "/")
		if clean != DirName && !strings.HasPrefix(clean, DirName+"/") {
			return fmt.Errorf("refusing to write outside %s/: %s", DirName, a.RelPath)
		}
		abs := filepath.Join(root, filepath.FromSlash(clean))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return fmt.Errorf("creating %s: %w", filepath.Dir(abs), err)
		}
		if err := os.WriteFile(abs, a.Content, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", clean, err)
		}
	}
	return nil
}

// sortedKeys returns a map's keys in ascending order.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
