package design

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The webui feedback write path and the Go feedback reader are separate
// implementations of the SP-140-4 §4d schema, in separate languages, and until
// this test nothing asserted they agree: the Go acceptance tests seeded their
// fixture with a hand-rolled constant carrying a comment claiming it was "what
// the webui write path produces", which no test checked.
//
// A divergence is silent and severe. If the webui wrote a different shape or
// put the file at a different path, the human's annotation would never surface
// as pending, the agent's loop would never start, and every existing test on
// both sides would still pass because each only exercises its own half.
//
// The fixture is generated by `scripts/gen-feedback-fixture.mts` from the real
// webui builder, and carries both halves of the webui's decision: the document
// AND the filename it would write to. Reading the filename from the artifact
// (rather than recomputing the rule here) is what lets this test fail if the
// webui's path convention drifts — recomputing it in Go would move both sides
// together and hide exactly the bug this guards.

type feedbackContractArtifact struct {
	Target   string          `json:"target"`
	Filename string          `json:"filename"`
	Document json.RawMessage `json:"document"`
}

func loadFeedbackContractArtifact(t *testing.T) feedbackContractArtifact {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "webui-feedback", "new-annotation.json"))
	require.NoError(t, err,
		"the webui-produced fixture must exist; regenerate with `npx tsx scripts/gen-feedback-fixture.mts`")

	var artifact feedbackContractArtifact
	require.NoError(t, json.Unmarshal(raw, &artifact))
	require.NotEmpty(t, artifact.Filename, "the artifact records the webui's filename decision")
	require.NotEmpty(t, artifact.Document)
	return artifact
}

// TestFeedbackContract_WebuiProducedDocumentIsPending puts the webui's document
// where the webui says it belongs and asserts the real Go reader sees it as a
// pending annotation on the right target.
func TestFeedbackContract_WebuiProducedDocumentIsPending(t *testing.T) {
	artifact := loadFeedbackContractArtifact(t)

	var doc map[string]any
	require.NoError(t, json.Unmarshal(artifact.Document, &doc))

	// The contract's required fields, as the webui writes them.
	for _, field := range []string{"target", "status", "resolution", "annotations"} {
		assert.Contains(t, doc, field, "§4d field %q is part of the cross-language contract", field)
	}
	assert.Equal(t, "changes-requested", doc["status"],
		"§4d: a newly written annotation is pending")

	annotations, ok := doc["annotations"].([]any)
	require.True(t, ok)
	require.Len(t, annotations, 1)
	first, ok := annotations[0].(map[string]any)
	require.True(t, ok)
	for _, field := range []string{"id", "at", "area", "note", "resolved", "created"} {
		assert.Contains(t, first, field, "§4d annotation field %q", field)
	}
	assert.Equal(t, false, first["resolved"], "a new annotation starts unresolved")

	// The webui keys the file on the annotated asset's stem; use the filename
	// the webui itself computed, so a stem regression (the
	// `design/feedback/design/wireframes/login.json` doubling the item-4.8
	// review caught) fails here rather than being papered over.
	root := t.TempDir()
	feedbackDir := filepath.Join(root, DirName, FeedbackSubdir)
	require.NoError(t, os.MkdirAll(feedbackDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(feedbackDir, artifact.Filename), artifact.Document, 0o644))

	states, err := ScanFeedbackDir(root)
	require.NoError(t, err)
	require.Len(t, states, 1,
		"the Go reader must find the webui-written file at the webui's own filename (%s)", artifact.Filename)

	state := states[0]
	assert.True(t, state.Valid, "the webui-produced document must parse as valid")
	assert.Equal(t, artifact.Target, state.Target)
	assert.Equal(t, "changes-requested", state.Status)
	assert.Equal(t, 1, state.Annotations)
	assert.Equal(t, 0, state.Resolved)
	assert.True(t, state.IsPending(), "the agent's loop must see the human's annotation as pending")

	// And the validator — the surface design_validate reads — accepts it.
	findings, err := ValidateFeedbackDir(root)
	require.NoError(t, err)
	assert.Empty(t, findings, "a webui-produced feedback file must validate cleanly")
}

// TestFeedbackContract_WebuiFilenameIsAStem pins the path rule itself. The
// webui must write `login.json` in design/feedback/, not a path derived from
// the full asset path.
func TestFeedbackContract_WebuiFilenameIsAStem(t *testing.T) {
	artifact := loadFeedbackContractArtifact(t)

	assert.NotContains(t, artifact.Filename, "/",
		"the feedback filename is a bare stem, not a path (%s)", artifact.Filename)
	assert.NotContains(t, artifact.Filename, "design",
		"the design/ prefix must not survive into the filename (%s)", artifact.Filename)
	assert.Equal(t, "login.json", artifact.Filename)
}
