//go:build ignore
// +build ignore

// Code generator for provider auto-discovery
// Run with: go run generate_providers.go
// This script reads provider configs from configs/ directory and generates
// all the registration code to avoid hardcoding provider names in multiple places.

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// ProviderConfig represents a minimal subset of the provider config needed for code generation
type ProviderConfig struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Auth        struct {
		Type   string `json:"type"`
		EnvVar string `json:"env_var"`
	} `json:"auth"`
}

func main() {
	// Get the directory where this script is located
	scriptDir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}

	configsDir := filepath.Join(scriptDir, "configs")

	// Read all provider configs
	providers, err := loadProviderConfigs(configsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading provider configs: %v\n", err)
		os.Exit(1)
	}

	// Sort providers by name for consistent output
	sort.Slice(providers, func(i, j int) bool {
		return providers[i].Name < providers[j].Name
	})

	// Generate provider_gen.go
	if err := generateProviderGen(providers, scriptDir); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating provider_gen.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated provider_gen.go with %d providers\n", len(providers))
}

func loadProviderConfigs(configsDir string) ([]ProviderConfig, error) {
	var providers []ProviderConfig

	entries, err := os.ReadDir(configsDir)
	if err != nil {
		return nil, fmt.Errorf("reading configs directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}

		configPath := filepath.Join(configsDir, entry.Name())
		data, err := os.ReadFile(configPath)
		if err != nil {
			return nil, fmt.Errorf("reading config file %s: %w", configPath, err)
		}

		var config ProviderConfig
		if err := json.Unmarshal(data, &config); err != nil {
			return nil, fmt.Errorf("parsing config file %s: %w", configPath, err)
		}

		// Extract provider name from filename if not set
		if config.Name == "" {
			base := filepath.Base(configPath)
			config.Name = base[:len(base)-5] // Remove .json extension
		}

		providers = append(providers, config)
	}

	return providers, nil
}

func generateProviderGen(providers []ProviderConfig, outputDir string) error {
	data := struct {
		Providers []ProviderConfig
	}{
		Providers: providers,
	}

	// Create template and register helper functions
	tmpl := template.New("provider_gen").Funcs(template.FuncMap{
		"constantName": constantName,
		"displayName":  displayName,
	})

	tmpl = template.Must(tmpl.Parse(providerGenTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Write to provider_gen.go
	outputPath := filepath.Join(outputDir, "provider_gen.go")
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("writing provider_gen.go: %w", err)
	}

	return nil
}

const providerGenTemplate = `// Code generated by generate_providers.go. DO NOT EDIT.
//go:generate go run generate_providers.go

package providers

import (
	"fmt"
	"strings"
)

// ClientType constants for all providers
// These are auto-generated from provider configs (as strings to avoid import cycles)
const (
{{range .Providers}}
	{{constantName .Name}}ClientType = "{{.Name}}"{{end}}
)

// AllProviderNames returns all provider names as strings
func AllProviderNames() []string {
	return []string{
{{range .Providers}}
		"{{.Name}}",{{end}}
	}
}

// StringToClientType converts a string to ClientType (as string)
// This replaces the hardcoded ParseProviderName function
func StringToClientType(name string) (string, error) {
	normalized := strings.ToLower(strings.TrimSpace(name))

	// Handle special providers first
	switch normalized {
	case "ollama":
		return "ollama", nil
	case "test":
		return "test", nil
	case "editor":
		return "editor", nil
	}

	switch normalized {
{{range .Providers}}
	case "{{.Name}}":
		return "{{.Name}}", nil
{{end}}
	default:
		if normalized != "" {
			// For custom providers or future additions
			return normalized, nil
		}
		return "", fmt.Errorf("unknown provider: %s", name)
	}
}

// ClientTypeToString converts ClientType (as string) to string
// This replaces the hardcoded mapClientTypeToString function
func ClientTypeToString(ct string) string {
	// Handle special providers first
	switch ct {
	case "ollama":
		return "ollama"
	case "test":
		return "test"
	case "editor":
		return "editor"
	}

	switch ct {
{{range .Providers}}
	case "{{.Name}}":
		return "{{.Name}}"
{{end}}
	default:
		// For custom providers or future additions
		return ct
	}
}

// ProviderRequiresAPIKey returns whether a provider requires an API key
func ProviderRequiresAPIKey(name string) bool {
	normalized := strings.ToLower(strings.TrimSpace(name))

	// Handle special providers first
	switch normalized {
	case "ollama", "ollama-local", "test", "editor":
		return false
	}

	switch normalized {
{{range .Providers}}
	case "{{.Name}}":
		return {{if ne .Auth.Type "none"}}true{{else}}false{{end}}
{{end}}
	default:
		// Default to requiring key for unknown providers
		return true
	}
}

// ProviderEnvVar returns the environment variable name for a provider's API key
func ProviderEnvVar(name string) string {
	normalized := strings.ToLower(strings.TrimSpace(name))
	switch normalized {
{{range .Providers}}
	case "{{.Name}}":
		return "{{.Auth.EnvVar}}"
{{end}}
	// Special providers (no config files)
	case "jinaai":
		return "JINA_API_KEY"
	default:
		return ""
	}
}

// KnownProviders returns the list of known built-in provider names
// This replaces the hardcoded knownProviderNames list in api_keys.go
func KnownProviders() []string {
	return []string{
{{range .Providers}}
		"{{.Name}}",{{end}}
		// Special providers (no config files)
		"ollama",
		"ollama-local",
		"test",
		"editor",
		"jinaai",
	}
}

// ProviderDisplayNames returns a map of provider names to display names.
// Values prefer the per-config display_name field (single source of truth
// in pkg/agent_providers/configs/*.json); the hardcoded switch in
// generate_providers.go::displayName is kept as a transitional fallback
// for configs that haven't been backfilled yet.
func ProviderDisplayNames() map[string]string {
	return map[string]string{
{{range .Providers}}
		"{{.Name}}": "{{if .DisplayName}}{{.DisplayName}}{{else}}{{displayName .Name}}{{end}}",{{end}}
		// Special providers (no config files)
		"ollama": "Ollama (Local)",
		"ollama-local": "Ollama (Local)",
		"test": "Test Provider",
		"editor": "Editor Mode",
		"jinaai": "JinaAI",
	}
}
`

// Helper functions for template rendering

func constantName(name string) string {
	// Convert provider name to constant name
	// e.g., "openrouter" -> "OpenRouter"
	// e.g., "ollama-local" -> "OllamaLocal"
	parts := strings.Split(name, "-")
	var result string
	for _, part := range parts {
		if len(part) > 0 {
			result += strings.ToUpper(part[:1]) + strings.ToLower(part[1:])
		}
	}
	return result
}

func displayName(name string) string {
	// Convert provider name to display name
	// This is a simple conversion; can be enhanced with a config field
	switch name {
	case "ollama":
		return "Ollama (Local)"
	case "ollama-local":
		return "Ollama (Local)"
	case "ollama-cloud":
		return "Ollama (Cloud)"
	case "chutes":
		return "Chutes"
	case "openrouter":
		return "OpenRouter (Recommended)"
	case "zai":
		return "Z.AI"
	case "openai":
		return "OpenAI"
	case "deepinfra":
		return "DeepInfra"
	case "deepseek":
		return "DeepSeek"
	case "minimax":
		return "MiniMax"
	case "lmstudio":
		return "LM Studio"
	case "mistral":
		return "Mistral"
	case "cerebras":
		return "Cerebras"
	case "jinaai":
		return "JinaAI"
	default:
		// Capitalize first letter
		if len(name) > 0 {
			return strings.ToUpper(name[:1]) + strings.ToLower(name[1:])
		}
		return name
	}
}
