// Code generated by generate_providers.go. DO NOT EDIT.
//go:generate go run generate_providers.go

package providers

import (
	"fmt"
	"strings"
)

// ClientType constants for all providers
// These are auto-generated from provider configs (as strings to avoid import cycles)
const (

	CerebrasClientType = "cerebras"
	ChutesClientType = "chutes"
	DeepinfraClientType = "deepinfra"
	DeepseekClientType = "deepseek"
	LmstudioClientType = "lmstudio"
	MinimaxClientType = "minimax"
	MistralClientType = "mistral"
	OllamaCloudClientType = "ollama-cloud"
	OpenaiClientType = "openai"
	OpenrouterClientType = "openrouter"
	ZaiClientType = "zai"
	ZaiCodingClientType = "zai-coding"
)

// AllProviderNames returns all provider names as strings
func AllProviderNames() []string {
	return []string{

		"cerebras",
		"chutes",
		"deepinfra",
		"deepseek",
		"lmstudio",
		"minimax",
		"mistral",
		"ollama-cloud",
		"openai",
		"openrouter",
		"zai",
		"zai-coding",
	}
}

// StringToClientType converts a string to ClientType (as string)
// This replaces the hardcoded ParseProviderName function
func StringToClientType(name string) (string, error) {
	normalized := strings.ToLower(strings.TrimSpace(name))

	// Handle special providers first
	switch normalized {
	case "ollama":
		return "ollama", nil
	case "test":
		return "test", nil
	case "editor":
		return "editor", nil
	}

	switch normalized {

	case "cerebras":
		return "cerebras", nil

	case "chutes":
		return "chutes", nil

	case "deepinfra":
		return "deepinfra", nil

	case "deepseek":
		return "deepseek", nil

	case "lmstudio":
		return "lmstudio", nil

	case "minimax":
		return "minimax", nil

	case "mistral":
		return "mistral", nil

	case "ollama-cloud":
		return "ollama-cloud", nil

	case "openai":
		return "openai", nil

	case "openrouter":
		return "openrouter", nil

	case "zai":
		return "zai", nil

	case "zai-coding":
		return "zai-coding", nil

	default:
		if normalized != "" {
			// For custom providers or future additions
			return normalized, nil
		}
		return "", fmt.Errorf("unknown provider: %s", name)
	}
}

// ClientTypeToString converts ClientType (as string) to string
// This replaces the hardcoded mapClientTypeToString function
func ClientTypeToString(ct string) string {
	// Handle special providers first
	switch ct {
	case "ollama":
		return "ollama"
	case "test":
		return "test"
	case "editor":
		return "editor"
	}

	switch ct {

	case "cerebras":
		return "cerebras"

	case "chutes":
		return "chutes"

	case "deepinfra":
		return "deepinfra"

	case "deepseek":
		return "deepseek"

	case "lmstudio":
		return "lmstudio"

	case "minimax":
		return "minimax"

	case "mistral":
		return "mistral"

	case "ollama-cloud":
		return "ollama-cloud"

	case "openai":
		return "openai"

	case "openrouter":
		return "openrouter"

	case "zai":
		return "zai"

	case "zai-coding":
		return "zai-coding"

	default:
		// For custom providers or future additions
		return ct
	}
}

// ProviderRequiresAPIKey returns whether a provider requires an API key
func ProviderRequiresAPIKey(name string) bool {
	normalized := strings.ToLower(strings.TrimSpace(name))

	// Handle special providers first
	switch normalized {
	case "ollama", "ollama-local", "test", "editor":
		return false
	}

	switch normalized {

	case "cerebras":
		return true

	case "chutes":
		return true

	case "deepinfra":
		return true

	case "deepseek":
		return true

	case "lmstudio":
		return false

	case "minimax":
		return true

	case "mistral":
		return true

	case "ollama-cloud":
		return true

	case "openai":
		return true

	case "openrouter":
		return true

	case "zai":
		return true

	case "zai-coding":
		return true

	default:
		// Default to requiring key for unknown providers
		return true
	}
}

// ProviderEnvVar returns the environment variable name for a provider's API key
func ProviderEnvVar(name string) string {
	normalized := strings.ToLower(strings.TrimSpace(name))
	switch normalized {

	case "cerebras":
		return "CEREBRAS_API_KEY"

	case "chutes":
		return "CHUTES_API_KEY"

	case "deepinfra":
		return "DEEPINFRA_API_KEY"

	case "deepseek":
		return "DEEPSEEK_API_KEY"

	case "lmstudio":
		return ""

	case "minimax":
		return "MINIMAX_API_KEY"

	case "mistral":
		return "MISTRAL_API_KEY"

	case "ollama-cloud":
		return "OLLAMA_API_KEY"

	case "openai":
		return "OPENAI_API_KEY"

	case "openrouter":
		return "OPENROUTER_API_KEY"

	case "zai":
		return "ZAI_API_KEY"

	case "zai-coding":
		return "ZAI_CODING_API_KEY"

	// Special providers (no config files)
	case "jinaai":
		return "JINA_API_KEY"
	default:
		return ""
	}
}

// KnownProviders returns the list of known built-in provider names
// This replaces the hardcoded knownProviderNames list in api_keys.go
func KnownProviders() []string {
	return []string{

		"cerebras",
		"chutes",
		"deepinfra",
		"deepseek",
		"lmstudio",
		"minimax",
		"mistral",
		"ollama-cloud",
		"openai",
		"openrouter",
		"zai",
		"zai-coding",
		// Special providers (no config files)
		"ollama",
		"ollama-local",
		"test",
		"editor",
		"jinaai",
	}
}

// ProviderDisplayNames returns a map of provider names to display names.
// Values prefer the per-config display_name field (single source of truth
// in pkg/agent_providers/configs/*.json); the hardcoded switch in
// generate_providers.go::displayName is kept as a transitional fallback
// for configs that haven't been backfilled yet.
func ProviderDisplayNames() map[string]string {
	return map[string]string{

		"cerebras": "Cerebras",
		"chutes": "Chutes",
		"deepinfra": "DeepInfra",
		"deepseek": "DeepSeek",
		"lmstudio": "LM Studio",
		"minimax": "MiniMax",
		"mistral": "Mistral",
		"ollama-cloud": "Ollama (Cloud)",
		"openai": "OpenAI",
		"openrouter": "OpenRouter (Recommended)",
		"zai": "Z.AI",
		"zai-coding": "GLM Coding Plan",
		// Special providers (no config files)
		"ollama": "Ollama (Local)",
		"ollama-local": "Ollama (Local)",
		"test": "Test Provider",
		"editor": "Editor Mode",
		"jinaai": "JinaAI",
	}
}
